version: "3.9"
services:
  nginx-router:
    image: "nginx:latest"
    volumes:
      - type: bind
        source: ./nginxconfig/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - service1
  service1:
    image: "final_app"
    expose:
      - "80"
